// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr3icEja3B45Z1hBGSF1mii696EXFIT9o',
    appId: '1:349541614927:web:3eb33afbe7c1ddb9f1b13a',
    messagingSenderId: '349541614927',
    projectId: 'taller-173fd',
    authDomain: 'taller-173fd.firebaseapp.com',
    databaseURL: 'https://taller-173fd-default-rtdb.firebaseio.com',
    storageBucket: 'taller-173fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj3qt--X7Vb4E059IkMK43eFX3pm5uyzc',
    appId: '1:349541614927:android:eb769702d9d93d52f1b13a',
    messagingSenderId: '349541614927',
    projectId: 'taller-173fd',
    databaseURL: 'https://taller-173fd-default-rtdb.firebaseio.com',
    storageBucket: 'taller-173fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSRL82GNrRqXFC0DaWHSKotlr4lG-rOw',
    appId: '1:349541614927:ios:6551938b72785dc7f1b13a',
    messagingSenderId: '349541614927',
    projectId: 'taller-173fd',
    databaseURL: 'https://taller-173fd-default-rtdb.firebaseio.com',
    storageBucket: 'taller-173fd.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANSRL82GNrRqXFC0DaWHSKotlr4lG-rOw',
    appId: '1:349541614927:ios:6551938b72785dc7f1b13a',
    messagingSenderId: '349541614927',
    projectId: 'taller-173fd',
    databaseURL: 'https://taller-173fd-default-rtdb.firebaseio.com',
    storageBucket: 'taller-173fd.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr3icEja3B45Z1hBGSF1mii696EXFIT9o',
    appId: '1:349541614927:web:b9a75bda6e6a7886f1b13a',
    messagingSenderId: '349541614927',
    projectId: 'taller-173fd',
    authDomain: 'taller-173fd.firebaseapp.com',
    databaseURL: 'https://taller-173fd-default-rtdb.firebaseio.com',
    storageBucket: 'taller-173fd.appspot.com',
  );
}
